# Generated by Django 6.0.2 on 2026-02-20 03:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('face_value', models.IntegerField(blank=True, null=True)),
                ('picture_value', models.CharField(blank=True, choices=[('A', 'Ace'), ('K', 'King'), ('Q', 'Queen'), ('J', 'Jack'), ('JOKER', 'Joker')], max_length=10, null=True)),
                ('suit', models.CharField(blank=True, choices=[('HEARTS', 'Hearts'), ('SPADES', 'Spades'), ('CLUBS', 'Clubs'), ('DIAMONDS', 'Diamonds')], max_length=10, null=True)),
                ('position', models.PositiveIntegerField()),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='card_game.deck')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('face_value__isnull', False), ('picture_value__isnull', True)), models.Q(('face_value__isnull', True), ('picture_value__isnull', False)), _connector='OR'), name='card_face_or_picture_exactly_one'), models.CheckConstraint(condition=models.Q(models.Q(('picture_value', 'JOKER'), ('suit__isnull', True)), models.Q(models.Q(('picture_value', 'JOKER'), _negated=True), ('suit__isnull', False)), _connector='OR'), name='card_suit_required_unless_joker')],
                'unique_together': {('deck', 'position')},
            },
        ),
    ]
